name: Auto-merge Dependabot PRs

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour (can adjust the frequency)
  workflow_dispatch:  # Allows manual trigger

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Fetch all open Dependabot PRs
      run: |
        pr_list=$(gh pr list --author dependabot[bot] --base dev --json number,compatibility_score)
        echo "Found PRs: $pr_list"
        echo "$pr_list" > pr_list.json

    - name: Auto-merge PRs with 100% compatibility
      run: |
        for row in $(jq -c '.[]' pr_list.json); do
          pr_number=$(echo $row | jq -r '.number')
          compatibility_score=$(echo $row | jq -r '.compatibility_score')

          if [[ $compatibility_score == "100" ]]; then
            echo "PR #$pr_number has 100% compatibility, merging..."
            gh pr merge $pr_number --auto --squash --delete-branch
          else
            echo "PR #$pr_number does not have 100% compatibility, skipping..."
          fi
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
